name: CI

on:
  push:
    branches:
      - master

jobs:
  lint_and_unit_tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Lint
        run: pnpm run lint

      - name: Unit Tests
        run: pnpm run test:coverage

#
#  e2e_tests:
#   runs-on: ubuntu-latest
#    needs: lint_and_unit_tests
#   strategy:
#      fail-fast: false
#      matrix:
#        containers: [1, 2]
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v3
#      - name: Playwright Test
#        uses: microsoft/playwright-github-action@v1
#        with:
#          browser: all
#
#      - name: Install pnpm
#        run: npm install -g pnpm
#
#      - name: Install dependencies
#        run: pnpm install
#
#      - name: Start server
#        run: pnpm run dev
#      - name: Run Playwright tests
#        run: pnpm test:e2e

  analysis:
    runs-on: ubuntu-latest
    needs: lint_and_unit_tests
    steps:
      - name: Analyze with SonarCloud
        uses: SonarSource/sonarcloud-github-action@de2e56b42aa84d0b1c5b622644ac17e505c9a049
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: -Dsonar.projectKey=italofelipe_nextjs-docker
            -Dsonar.organization=sensoriumit

  publish_chromatic:
    runs-on: ubuntu-latest
    needs: analysis
    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: pnpm install

      - name: Publish to Chromatic
        uses: chromaui/action@v1
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
